### ISSUE TITLE
Import xprv text

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianCosigner-iOS#14]
We need to have some way to import an xprv (or seed to derive the xprv) from the "Cosigners/Add Cosigners". In particular, ability to import from the 6 types of data in the "Cosigner Detail" (3 QRs and 3 text from clipboard).

One particular testing use case is using simulator, I can't use camera, so I can't import a test xprv I made on my phone's Gordian Cosigner.

**Comment by Fonta1n3** [comment]
From the cosigners parent view tap the + button in top right > tap import. You can then scan or paste the text of a crypto-hdkey, crypto-account, bip39 words or a xpub/xprv cosigner in plain text format.

You can not paste an xprv without origin info as origin info is always required.

Closing this as this functionality was just added, if it does not work for you feel free to reopen.
