### ISSUE TITLE
Can't do universal "Any Mac" build on m1, get "build only device cannot be used"

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianCosigner-iOS#17]
![](https://user-images.githubusercontent.com/69103/104767483-143cd380-5721-11eb-9b1b-fbfc9f87ecd7.png)

**Comment by Fonta1n3** [comment]
That's expected, you want to build on "my mac".

**Comment by ChristopherA** [comment]
Thus probably should not be closed. Doesn’t “Any Mac” create a universal binary?

**Comment by Fonta1n3** [comment]
You use "any mac" or "any ios" for submitting an archived build to the app store, not for running the app.

**Comment by Fonta1n3** [comment]
It should be closed as its not an issue. What is it you are trying to achieve?

**Comment by ChristopherA** [comment]
Just want to confirm that a universal Mac version is buildable for distribution. I can’t seem to do it.

**Comment by Fonta1n3** [comment]
> Just want to confirm that a universal Mac version is buildable for distribution. I can’t seem to do it.

Well you would need to set the scheme to "archive", then archive the app using the "any mac" build target.
