### ISSUE TITLE
Remove trash for unremovable 

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianCosigner-iOS#19]
The trash buttons should not be there if no data.

I also think we should change xprv label to “private keyset” — as it is more than the xprv as it has path.

maybe later we should have a + button to re-add (and test against xpub) empty seed & xprv.

![4E94945B-ECBF-49EE-B459-0A9B7E5F193D](https://user-images.githubusercontent.com/69103/105572857-83608c00-5d0e-11eb-93d1-3c34f4403563.jpeg)

**Comment by Fonta1n3** [comment]
fixed as per #18
