### ISSUE TITLE
Adding notes to cosigners

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianCosigner-iOS#20]
I’d really like to not only have label for cosigners, but add notes (and be able to optionally import/export them, which I think wolf now supports for seeds)

Use case: “this account is for paying off house or retirement; the account words for this cosigner are on titanium in safe deposit box at xxx bank; my wife’s is the primary cosigner, this is more for emergencies; a backup set of sskr’s were given to x, y, & z)”

**Comment by Fonta1n3** [comment]
fixed as per #18
