### ISSUE TITLE
Changed Label Not Shown in Export

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianCosigner-iOS#21]
I changed the label on my cosigner in the details view:

 But when I go to export it, it still has the old label.

Related, maybe this label should wrap? There does seem to be room. Maybe also a small version of the LifeHash under everything too.

![E81BBF35-DC35-404D-85A3-22E6239F077F](https://user-images.githubusercontent.com/69103/105781767-f6911a80-5f27-11eb-86c6-25e9d46a6850.png)

**Comment by Fonta1n3** [comment]
fixed as per #18
