### ISSUE TITLE
Feature: QR Import of ur:crypto-seed

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianCosigner-iOS#23]
In the Cosigner pane, if you hit +, and import, but are presented with something other than a 48 xpub or xprv, it should do the following (and maybe ask are you sure:

Clipboard or QR:

- ur:crypto-seed --> derive the Cosigner and Cosigner private keys and throw away the seed.
- bip39 words --> derive the Cosigner and Cosigner private keys and throw away the words.
- master xprv --> derive the Cosigner and Cosigner private key sand throw away the master xprv.
- master xpub --> derive the Cosigner only and throw away the master xpub.

- non-48 xprv or xpub but does have master key finger print --> warn the user, allow accept or cancel.
- non-48 xprv or xpub WITHOUT master key finger print --> tell the user no, and suggest the user enter one of the other options.

@wolfmcnally — am I missing any other options?

-- Christopher Allen

**Comment by gorazdko** [comment]
> master xpub --> derive the Cosigner only and throw away the master xpub.

You can only derive a cosigner from a master privkey

Also relevant: UR spec says "A master key is always private, has no use or derivation information" ([1](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-007-hdkey.md#cddl-for-hdkey)) . As far as I understand master pubkey can't even be conveyed over UR, or should a master pubkey be treated as a derived key? Not sure though what it would be useful for...

**Comment by Fonta1n3** [comment]
crypto-seed is now supported. Please reopen the issue if its not working for you.
