### ISSUE TITLE
Can't Read Warm Accounts from Gordian Wallet

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianCosigner-iOS#33]
Here's the second issue with compatibility between Wallet and CS:

A more meaningful usage might be generating a warm account on Wallet, and then using GCS to store the offline key and sign with it as necessary. Unfortunately, exporting the offline key from Wallet to CS seems to fail silently.

I exported the following QR as the warm account offline key from Wallet. When I tried to import it as a cosigner into GCS, it took a picture and then silently failed. It didn't do anything with the picture, and it left me in the camera mode, but stopped taking future pictures.

![bad-qr](https://user-images.githubusercontent.com/1110886/108268498-afeea480-7110-11eb-9ccb-8180704c0c36.jpg)

**Comment by ChristopherA** [comment]
I scanned this QR Vault, and I get:

1. cactus
2. abandon
3. abandon
4. abandon
5. abandon
6. gather
7. achieve
8. praise
9. length
10. avoid
11. abandon
12. license

Derivation: m/48'/1'/0'/2'/0
Birthblock: 1936528

**Comment by shannona** [comment]
I was able to import these words using the CREATE button and the import words function. But the issue with the QR code and especially its silent failure, remains.

**Comment by Fonta1n3** [comment]
This is not a "warm account", this is the bip39 mnemonic backup for one of the seeds in the warm account. The warm account backup QR is what we refer to as an "account map" and that is supported in Gordian Cosigner by navigating to the "account" tab, tapping + (in top right) > import.

To add the words simply paste them or scan a QR of the words in plain text by navigating to the "cosigner" tab > + > import.

In the meantime I have added an error alert for unsupported QR types which will be included in the next Cosigner update.
