### ISSUE TITLE
Integration Notes Needed for Spectre and LetheKit

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianCosigner-iOS#36]
It'd be useful to talk about Catalyst integrating with LetheKit and with Spectre. @gorazdko is this something you could take on?

These would be updates to: https://github.com/BlockchainCommons/GordianCosigner-Catalyst/blob/master/Docs/Integrating.md

Thanks!

**Comment by gorazdko** [comment]
Will do!
