### ISSUE TITLE
Update Social Media Preview with New Screenshots

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianCosigner-iOS#6]
Base them on 0.1.5.

**Comment by shannona** [comment]
Social Media is updated with 0.1.5 screenshots; the PSD, PNG, and JPG files for the repo will be in today's PR.

**Comment by ChristopherA** [comment]
Text on Logo should be Cosigner.

**Comment by shannona** [comment]
Right! Thanks.

**Comment by shannona** [comment]
(Resolved.)
