### ISSUE TITLE
Co-signer Labels Incorrect

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/GordianCosigner-iOS#8]
Had some inconsistent/weird updates of co-signer labels.

Here's what I did:

1.) Renamed one of my co-signers from "co-signer" to "offline"
2.) Renamed the corresponding seed from "co-signer" to "offline"
3.) On the pop-up, told it that it could update the co-signer too.
4.) Went to create a new account, and when I added co-signer, it gave me three options: "offline", "offline", and "offline"
5.) Verified that my list of co-signers shows them as "Trezor", "chris allen", and "offline".
6.) Added that first "offline" cosigner, and saw it now listed as "chris allen"

I dunno if 1-3 are relevant are not, but that's the whole sequence.

**Comment by shannona** [comment]
![IMG_0944](https://user-images.githubusercontent.com/1110886/102934321-fcd33900-4447-11eb-9649-0308b046636a.jpg)
![IMG_0945](https://user-images.githubusercontent.com/1110886/102934332-0066c000-4448-11eb-9883-3273606c78ad.jpg)
![IMG_0946](https://user-images.githubusercontent.com/1110886/102934337-0361b080-4448-11eb-8efb-98407402cc41.jpg)

**Comment by Fonta1n3** [comment]
should be fixed as per #4
